# Generated by Django 3.0.8 on 2020-08-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200831_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
    ]
