# Generated by Django 3.0.8 on 2020-07-23 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('focal_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aperture', models.CharField(max_length=10)),
                ('shutter_speed_sec', models.DecimalField(decimal_places=2, max_digits=6)),
                ('iso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_title', models.CharField(max_length=254)),
                ('img_taken', models.DateField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img_status', models.BinaryField()),
                ('vol_sold', models.IntegerField()),
                ('img_rating', models.IntegerField()),
                ('img_data_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image_Data')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
