# Generated by Django 3.0.8 on 2020-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200723_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_status',
            field=models.BinaryField(max_length=1),
        ),
    ]
