# Generated by Django 3.0.8 on 2020-07-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200723_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_status',
            field=models.IntegerField(),
        ),
    ]
