# Generated by Django 3.0.8 on 2020-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200723_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_data',
            name='iso',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='image_data',
            name='shutter_speed_sec',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
