# Generated by Django 3.0.8 on 2020-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20200723_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_data',
            name='focal_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image_data',
            name='iso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image_data',
            name='shutter_speed_sec',
            field=models.IntegerField(),
        ),
    ]
