# Generated by Django 3.0.8 on 2020-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20200723_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_title',
            field=models.CharField(max_length=75),
        ),
    ]
