# Generated by Django 3.0.8 on 2020-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20200723_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tmnl_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
