# Generated by Django 3.0.8 on 2020-08-17 19:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_image_tmnl_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_data',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
