# Generated by Django 3.0.8 on 2020-08-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20200817_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_taken',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='vol_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image_data',
            name='focal_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image_data',
            name='iso',
            field=models.IntegerField(default=0),
        ),
    ]
