# Generated by Django 3.0.8 on 2020-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20200818_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_rating',
            field=models.IntegerField(default=0),
        ),
    ]
