# Generated by Django 3.0.8 on 2020-08-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_auto_20200818_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_taken',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_data',
            name='focal_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_data',
            name='iso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_data',
            name='shutter_speed_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
