# Generated by Django 3.0.8 on 2020-08-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20200819_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='prev_img',
        ),
    ]
