# Generated by Django 3.0.8 on 2020-08-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_auto_20200822_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='prev_img',
            field=models.ImageField(upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='tmnl_img',
            field=models.ImageField(upload_to='', verbose_name=''),
        ),
    ]
