# Generated by Django 3.0.8 on 2020-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_auto_20200822_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='prev_img',
            field=models.ImageField(upload_to='user_images/', verbose_name=''),
        ),
    ]
