# Generated by Django 3.0.8 on 2020-08-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_auto_20200822_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_status',
        ),
        migrations.AlterField(
            model_name='image',
            name='tmnl_img',
            field=models.ImageField(upload_to='user_images/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='image',
            name='img_status',
            field=models.BooleanField(default=False),
        ),
    ]
