# Generated by Django 3.0.8 on 2020-08-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_auto_20200825_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_data',
            options={'verbose_name_plural': 'Image Data'},
        ),
        migrations.AlterModelOptions(
            name='imagecomments',
            options={'verbose_name_plural': 'Image Comments'},
        ),
    ]
