# Generated by Django 3.1.1 on 2020-09-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0022_auto_20200829_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageComments',
        ),
    ]
