# Generated by Django 3.0.8 on 2020-08-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seller',
            field=models.BooleanField(default=False),
        ),
    ]
